d: i r

i:
	../bin/naje 0
	../bin/naje 1
	../bin/naje 2
	../bin/naje 3
	../bin/naje 4
	../bin/naje 5
	../bin/naje 6
	../bin/naje 7
	../bin/naje 8
	../bin/naje 9
	../bin/naje 10
	../bin/naje 11
	../bin/naje 12
	../bin/naje 13
	../bin/naje 14
	../bin/naje 15
	../bin/naje 16
	../bin/naje 17
	../bin/naje 18
	../bin/naje 19
	../bin/naje 20
	../bin/naje 21
	../bin/naje 22
	../bin/naje 23
	../bin/naje 24
	../bin/naje 25
	../bin/naje 26

r:
	../bin/nga 0.nga >RESULTS
	../bin/nga 1.nga >>RESULTS
	../bin/nga 2.nga >>RESULTS
	../bin/nga 3.nga >>RESULTS
	../bin/nga 4.nga >>RESULTS
	../bin/nga 5.nga >>RESULTS
	../bin/nga 6.nga >>RESULTS
	../bin/nga 7.nga >>RESULTS
	../bin/nga 8.nga >>RESULTS
	../bin/nga 9.nga >>RESULTS
	../bin/nga 10.nga >>RESULTS
	../bin/nga 11.nga >>RESULTS
	../bin/nga 12.nga >>RESULTS
	../bin/nga 13.nga >>RESULTS
	../bin/nga 14.nga >>RESULTS
	../bin/nga 15.nga >>RESULTS
	../bin/nga 16.nga >>RESULTS
	../bin/nga 17.nga >>RESULTS
	../bin/nga 18.nga >>RESULTS
	../bin/nga 19.nga >>RESULTS
	../bin/nga 20.nga >>RESULTS
	../bin/nga 21.nga >>RESULTS
	../bin/nga 22.nga >>RESULTS
	../bin/nga 23.nga >>RESULTS
	../bin/nga 24.nga >>RESULTS
	../bin/nga 25.nga >>RESULTS
	../bin/nga 26.nga >>RESULTS

c:
	rm -f *.nga *.map RESULTS
